[versions]
kotlin = "2.0.20"
coroutines = "1.8.1"
tink = "1.13.0"
web3j = "4.9.7"
bitcoinj = "0.16.2"
slf4j = "2.0.13"
junit = "5.10.3"
gradle-plugin-kotlin = "2.0.20"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
web3j = { module = "org.web3j:core", version.ref = "web3j" }
bitcoinj = { module = "org.bitcoinj:bitcoinj-core", version.ref = "bitcoinj" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
