name: Qodana and Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master  # ← меняем master на main если у тебя main branch

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false
          push-fixes: 'none'

  build:
    runs-on: ubuntu-latest
    needs: qodana  # ← билд запустится только если Qodana пройдет
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create distribution
        run: ./gradlew :app:dist

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wallet-cli-dist
          path: dist/
          retention-days: 30